#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HttpMethod {
    Get,
    Post,
    Patch,
    Delete,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApiResource {
    pub path: &'static str,
    pub methods: &'static [HttpMethod],
    pub aggregate: &'static str,
    pub module: &'static str,
    pub purpose: &'static str,
    pub policy_hook_points: &'static [&'static str],
    pub emits_audit: bool,
}

pub fn milestone1_api_resources() -> Vec<ApiResource> {
    vec![
        ApiResource {
            path: "/v1/tenants",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "Tenant",
            module: "tenancy",
            purpose: "Provision and govern tenant boundaries, allowed regions, and sovereign posture.",
            policy_hook_points: &["TenantBoundaryChange"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/users",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "User",
            module: "identity",
            purpose: "Manage users synchronized from identity providers and local service accounts.",
            policy_hook_points: &["AssignmentChange"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/teams",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "Team",
            module: "identity",
            purpose: "Manage support, resolver, ownership, and CAB teams.",
            policy_hook_points: &["AssignmentChange"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/services",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ServiceOffering",
            module: "service_catalog",
            purpose: "Maintain business services used for impact, ownership, and change blast radius.",
            policy_hook_points: &[],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/catalog/categories",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ServiceCatalogCategory",
            module: "service_catalog",
            purpose: "Manage the user-facing request catalog taxonomy.",
            policy_hook_points: &["CatalogFulfillment"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/catalog/items",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ServiceCatalogItem",
            module: "service_catalog",
            purpose: "Define requestable services, variables, fulfillment handlers, and policy requirements.",
            policy_hook_points: &["CatalogFulfillment"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/incidents",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "Incident",
            module: "incidents",
            purpose: "Create, triage, assign, prioritize, link, and resolve operational incidents.",
            policy_hook_points: &[
                "TicketCreate",
                "TicketTransition",
                "AssignmentChange",
                "AiAssist",
            ],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/incidents/{incident_id}/worklogs",
            methods: &[HttpMethod::Get, HttpMethod::Post],
            aggregate: "IncidentWorklog",
            module: "incidents",
            purpose: "Append timeline entries without mutating historic comments.",
            policy_hook_points: &["AiAssist"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/service-requests",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ServiceRequest",
            module: "service_requests",
            purpose: "Submit catalog requests, track fulfillment, and manage variables.",
            policy_hook_points: &["TicketCreate", "TicketTransition", "CatalogFulfillment"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/service-requests/{request_id}/approvals",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "RequestApproval",
            module: "service_requests",
            purpose: "Issue and record request approval decisions.",
            policy_hook_points: &["ApprovalDecision"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/changes",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ChangeRequest",
            module: "changes",
            purpose: "Assess, authorize, schedule, implement, and review changes.",
            policy_hook_points: &[
                "TicketCreate",
                "TicketTransition",
                "ChangeSchedule",
                "ApprovalDecision",
            ],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/changes/{change_id}/tasks",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ChangeTask",
            module: "changes",
            purpose: "Track implementation and review tasks for a change.",
            policy_hook_points: &["TicketTransition"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/changes/{change_id}/approvals",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "ChangeApproval",
            module: "changes",
            purpose: "Capture CAB and emergency authorization decisions.",
            policy_hook_points: &["ApprovalDecision"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/problems",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "Problem",
            module: "problems",
            purpose: "Investigate recurring incidents, record root cause, and publish known errors.",
            policy_hook_points: &["TicketCreate", "TicketTransition", "KnowledgePublish"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/knowledge/articles",
            methods: &[HttpMethod::Get, HttpMethod::Post, HttpMethod::Patch],
            aggregate: "KnowledgeArticle",
            module: "knowledge",
            purpose: "Author, review, publish, and retire sovereign knowledge articles and runbooks.",
            policy_hook_points: &["KnowledgePublish", "AiAssist"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/knowledge/articles/{article_id}/feedback",
            methods: &[HttpMethod::Get, HttpMethod::Post],
            aggregate: "KnowledgeFeedback",
            module: "knowledge",
            purpose: "Collect article quality feedback for curation.",
            policy_hook_points: &[],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/policy/hooks",
            methods: &[
                HttpMethod::Get,
                HttpMethod::Post,
                HttpMethod::Patch,
                HttpMethod::Delete,
            ],
            aggregate: "PolicyHook",
            module: "policy_hooks",
            purpose: "Configure lifecycle, data residency, approval, redaction, and AI-assist enforcement hooks.",
            policy_hook_points: &["TenantBoundaryChange"],
            emits_audit: true,
        },
        ApiResource {
            path: "/v1/policy/evaluations",
            methods: &[HttpMethod::Get],
            aggregate: "PolicyEvaluation",
            module: "policy_hooks",
            purpose: "Read-only policy decision ledger for debugging and evidence.",
            policy_hook_points: &[],
            emits_audit: false,
        },
        ApiResource {
            path: "/v1/audit/events",
            methods: &[HttpMethod::Get],
            aggregate: "AuditEvent",
            module: "audit",
            purpose: "Query append-only evidence for access, mutations, approvals, policy decisions, and AI usage.",
            policy_hook_points: &["DataExport"],
            emits_audit: false,
        },
    ]
}
