#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableSpec {
    pub name: &'static str,
    pub entity: &'static str,
    pub module: &'static str,
    pub key: &'static str,
    pub tenant_scoped: bool,
    pub purpose: &'static str,
    pub columns: &'static [&'static str],
    pub indexes: &'static [&'static str],
}

pub fn milestone1_tables() -> Vec<TableSpec> {
    vec![
        TableSpec {
            name: "tenants",
            entity: "Tenant",
            module: "tenancy",
            key: "id",
            tenant_scoped: false,
            purpose: "Root tenancy, residency, sovereignty mode, and lifecycle state.",
            columns: &[
                "id",
                "slug",
                "display_name",
                "tier",
                "status",
                "primary_region",
                "allowed_regions",
                "sovereignty_policy",
                "created_at",
            ],
            indexes: &["unique(slug)", "status"],
        },
        TableSpec {
            name: "tenant_environments",
            entity: "TenantEnvironment",
            module: "tenancy",
            key: "id",
            tenant_scoped: true,
            purpose: "Per-tenant deployment environments and regional placement.",
            columns: &["id", "tenant_id", "name", "region", "status"],
            indexes: &["tenant_id,name", "tenant_id,region"],
        },
        TableSpec {
            name: "users",
            entity: "User",
            module: "identity",
            key: "id",
            tenant_scoped: true,
            purpose: "Human users mapped from sovereign identity providers.",
            columns: &[
                "id",
                "tenant_id",
                "external_subject",
                "email",
                "display_name",
                "status",
                "primary_team_id",
                "role_ids",
            ],
            indexes: &["tenant_id,email", "tenant_id,external_subject"],
        },
        TableSpec {
            name: "teams",
            entity: "Team",
            module: "identity",
            key: "id",
            tenant_scoped: true,
            purpose: "Resolver, owner, CAB, and support teams.",
            columns: &[
                "id",
                "tenant_id",
                "name",
                "status",
                "manager_user_id",
                "parent_team_id",
                "on_call_rotation_ref",
            ],
            indexes: &["tenant_id,name", "tenant_id,parent_team_id"],
        },
        TableSpec {
            name: "user_team_memberships",
            entity: "UserTeamMembership",
            module: "identity",
            key: "tenant_id,user_id,team_id",
            tenant_scoped: true,
            purpose: "Many-to-many team membership with primary-team marker.",
            columns: &["tenant_id", "user_id", "team_id", "is_primary"],
            indexes: &["tenant_id,user_id", "tenant_id,team_id"],
        },
        TableSpec {
            name: "roles",
            entity: "Role",
            module: "identity",
            key: "id",
            tenant_scoped: true,
            purpose: "Permission bundles for RBAC and policy expressions.",
            columns: &[
                "id",
                "tenant_id",
                "name",
                "permissions",
                "created_at",
                "updated_at",
                "version",
            ],
            indexes: &["tenant_id,name"],
        },
        TableSpec {
            name: "service_offerings",
            entity: "ServiceOffering",
            module: "service_catalog",
            key: "id",
            tenant_scoped: true,
            purpose: "Business/technical services affected by tickets and changes.",
            columns: &[
                "id",
                "tenant_id",
                "name",
                "owner_team_id",
                "status",
                "criticality",
                "support_tier",
                "data_classes",
            ],
            indexes: &["tenant_id,name", "tenant_id,owner_team_id"],
        },
        TableSpec {
            name: "service_catalog_categories",
            entity: "ServiceCatalogCategory",
            module: "service_catalog",
            key: "id",
            tenant_scoped: true,
            purpose: "Navigable service catalog taxonomy.",
            columns: &["id", "tenant_id", "name", "parent_id", "status"],
            indexes: &["tenant_id,parent_id", "tenant_id,name"],
        },
        TableSpec {
            name: "service_catalog_items",
            entity: "ServiceCatalogItem",
            module: "service_catalog",
            key: "id",
            tenant_scoped: true,
            purpose: "Requestable catalog items with variables and fulfillment hooks.",
            columns: &[
                "id",
                "tenant_id",
                "category_id",
                "name",
                "description",
                "status",
                "owner_team_id",
                "fulfillment_kind",
                "fulfillment_ref",
                "intake_schema_ref",
                "required_policy_hook_ids",
                "version",
            ],
            indexes: &["tenant_id,category_id", "tenant_id,status"],
        },
        TableSpec {
            name: "service_catalog_variables",
            entity: "CatalogVariable",
            module: "service_catalog",
            key: "tenant_id,item_id,key",
            tenant_scoped: true,
            purpose: "Typed intake fields for service catalog request submission.",
            columns: &[
                "tenant_id",
                "item_id",
                "key",
                "label",
                "required",
                "data_class",
            ],
            indexes: &["tenant_id,item_id"],
        },
        TableSpec {
            name: "incidents",
            entity: "Incident",
            module: "incidents",
            key: "id",
            tenant_scoped: true,
            purpose: "Operational break/fix records, SLA prioritisation, and service impact.",
            columns: &[
                "id",
                "tenant_id",
                "number",
                "title",
                "description",
                "status",
                "impact",
                "urgency",
                "priority",
                "channel",
                "caller_user_id",
                "affected_service_id",
                "owning_team_id",
                "assignee_user_id",
                "related_problem_id",
                "related_change_id",
                "sla_policy_id",
                "policy_hook_ids",
                "version",
            ],
            indexes: &[
                "tenant_id,number",
                "tenant_id,status,priority",
                "tenant_id,affected_service_id",
            ],
        },
        TableSpec {
            name: "incident_worklogs",
            entity: "IncidentWorklog",
            module: "incidents",
            key: "id",
            tenant_scoped: true,
            purpose: "Immutable internal/public incident timeline entries.",
            columns: &[
                "id",
                "tenant_id",
                "incident_id",
                "body",
                "internal",
                "created_at",
                "created_by",
            ],
            indexes: &["tenant_id,incident_id,created_at"],
        },
        TableSpec {
            name: "service_requests",
            entity: "ServiceRequest",
            module: "service_requests",
            key: "id",
            tenant_scoped: true,
            purpose: "Catalog-backed requests, fulfillment state, approvals, and variables.",
            columns: &[
                "id",
                "tenant_id",
                "number",
                "catalog_item_id",
                "requester_user_id",
                "requested_for_user_id",
                "status",
                "owning_team_id",
                "assignee_user_id",
                "due_at",
                "policy_hook_ids",
                "version",
            ],
            indexes: &[
                "tenant_id,number",
                "tenant_id,status",
                "tenant_id,catalog_item_id",
            ],
        },
        TableSpec {
            name: "service_request_variables",
            entity: "RequestVariableValue",
            module: "service_requests",
            key: "tenant_id,request_id,key",
            tenant_scoped: true,
            purpose: "Submitted request variable values, encrypted by data class where needed.",
            columns: &["tenant_id", "request_id", "key", "value", "data_class"],
            indexes: &["tenant_id,request_id"],
        },
        TableSpec {
            name: "request_approvals",
            entity: "RequestApproval",
            module: "service_requests",
            key: "id",
            tenant_scoped: true,
            purpose: "Approval chain for service request fulfillment.",
            columns: &[
                "id",
                "tenant_id",
                "request_id",
                "approver_user_id",
                "decision",
                "decided_at",
            ],
            indexes: &[
                "tenant_id,request_id",
                "tenant_id,approver_user_id,decision",
            ],
        },
        TableSpec {
            name: "change_requests",
            entity: "ChangeRequest",
            module: "changes",
            key: "id",
            tenant_scoped: true,
            purpose: "Standard/normal/emergency changes with risk, windows, plans, and CAB approvals.",
            columns: &[
                "id",
                "tenant_id",
                "number",
                "title",
                "description",
                "change_type",
                "risk",
                "status",
                "planned_start",
                "planned_end",
                "implementation_plan",
                "rollback_plan",
                "test_plan",
                "owning_team_id",
                "assignee_user_id",
                "policy_hook_ids",
                "version",
            ],
            indexes: &[
                "tenant_id,number",
                "tenant_id,status,planned_start",
                "tenant_id,risk",
            ],
        },
        TableSpec {
            name: "change_affected_services",
            entity: "ChangeRequest.affected_service_ids",
            module: "changes",
            key: "tenant_id,change_id,service_id",
            tenant_scoped: true,
            purpose: "Many-to-many blast-radius mapping from changes to services.",
            columns: &["tenant_id", "change_id", "service_id"],
            indexes: &["tenant_id,service_id"],
        },
        TableSpec {
            name: "change_tasks",
            entity: "ChangeTask",
            module: "changes",
            key: "id",
            tenant_scoped: true,
            purpose: "Implementation/review task checklist for changes.",
            columns: &[
                "id",
                "tenant_id",
                "change_id",
                "title",
                "owning_team_id",
                "assignee_user_id",
                "completed_at",
            ],
            indexes: &["tenant_id,change_id"],
        },
        TableSpec {
            name: "change_approvals",
            entity: "ChangeApproval",
            module: "changes",
            key: "id",
            tenant_scoped: true,
            purpose: "CAB and emergency approval decisions.",
            columns: &[
                "id",
                "tenant_id",
                "change_id",
                "approver_user_id",
                "approved",
                "decided_at",
            ],
            indexes: &["tenant_id,change_id", "tenant_id,approver_user_id,approved"],
        },
        TableSpec {
            name: "problems",
            entity: "Problem",
            module: "problems",
            key: "id",
            tenant_scoped: true,
            purpose: "Root-cause investigation, known error, and workaround lifecycle.",
            columns: &[
                "id",
                "tenant_id",
                "number",
                "title",
                "description",
                "status",
                "owning_team_id",
                "assignee_user_id",
                "root_cause",
                "workaround",
                "known_error_id",
                "version",
            ],
            indexes: &["tenant_id,number", "tenant_id,status"],
        },
        TableSpec {
            name: "problem_incidents",
            entity: "Problem.linked_incident_ids",
            module: "problems",
            key: "tenant_id,problem_id,incident_id",
            tenant_scoped: true,
            purpose: "Many-to-many relationship from incidents to root-cause problem records.",
            columns: &["tenant_id", "problem_id", "incident_id"],
            indexes: &["tenant_id,incident_id"],
        },
        TableSpec {
            name: "known_errors",
            entity: "KnownError",
            module: "problems",
            key: "id",
            tenant_scoped: true,
            purpose: "Reusable known-error records exposed to knowledge and incident deflection.",
            columns: &[
                "id",
                "tenant_id",
                "problem_id",
                "symptom",
                "workaround",
                "published_at",
            ],
            indexes: &["tenant_id,problem_id"],
        },
        TableSpec {
            name: "knowledge_articles",
            entity: "KnowledgeArticle",
            module: "knowledge",
            key: "id",
            tenant_scoped: true,
            purpose: "Versioned knowledge/runbook bodies stored in sovereign object storage.",
            columns: &[
                "id",
                "tenant_id",
                "title",
                "article_type",
                "status",
                "audience",
                "owner_team_id",
                "body_storage_ref",
                "source_problem_id",
                "review_due_at",
                "policy_hook_ids",
                "version",
            ],
            indexes: &[
                "tenant_id,status,audience",
                "tenant_id,owner_team_id",
                "tenant_id,review_due_at",
            ],
        },
        TableSpec {
            name: "knowledge_feedback",
            entity: "KnowledgeFeedback",
            module: "knowledge",
            key: "id",
            tenant_scoped: true,
            purpose: "Article usefulness and feedback loop for curation.",
            columns: &[
                "id",
                "tenant_id",
                "article_id",
                "user_id",
                "helpful",
                "comment",
                "created_at",
            ],
            indexes: &["tenant_id,article_id,created_at"],
        },
        TableSpec {
            name: "policy_hooks",
            entity: "PolicyHook",
            module: "policy_hooks",
            key: "id",
            tenant_scoped: true,
            purpose: "Tenant-configured policy attachment points for lifecycle enforcement.",
            columns: &[
                "id",
                "tenant_id",
                "name",
                "hook_point",
                "enforcement",
                "applies_to_resource_types",
                "expression_ref",
                "active",
            ],
            indexes: &["tenant_id,hook_point,active"],
        },
        TableSpec {
            name: "policy_evaluations",
            entity: "PolicyEvaluation",
            module: "policy_hooks",
            key: "id",
            tenant_scoped: true,
            purpose: "Decision log and obligations emitted by policy hooks.",
            columns: &[
                "id",
                "tenant_id",
                "hook_id",
                "hook_point",
                "resource_type",
                "resource_id",
                "actor",
                "data_classes",
                "decision",
                "obligations",
                "reason",
                "evaluated_at",
            ],
            indexes: &[
                "tenant_id,resource_type,resource_id",
                "tenant_id,hook_id,evaluated_at",
            ],
        },
        TableSpec {
            name: "audit_events",
            entity: "AuditEvent",
            module: "audit",
            key: "id",
            tenant_scoped: true,
            purpose: "Append-only audit stream for all data mutations, access, approvals, and policy decisions.",
            columns: &[
                "id",
                "tenant_id",
                "occurred_at",
                "actor",
                "action",
                "resource_type",
                "resource_id",
                "data_classes",
                "source_ip",
                "correlation_id",
                "before_hash",
                "after_hash",
                "policy_evaluation_id",
                "immutable_sequence",
            ],
            indexes: &[
                "tenant_id,occurred_at",
                "tenant_id,resource_type,resource_id",
                "correlation_id",
            ],
        },
    ]
}
